name: CI
on: [push, pull_request]

jobs:
  tests:
    name: Unit tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      # Without disabling autocrlf, JSON files for tests are converted and tests will fail
      - run: git config --global core.autocrlf false
        if: matrix.os == 'windows-latest'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm ci
      - run: npm run build
      - run: bash ./scripts/collect-repos-simple.bash
        shell: bash
      - run: npm run test
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm ci
      - run: npm run lint
